spring:
  datasource:
    dynamic:
      primary: mysql #设置默认的数据源或者数据源组,默认值即为master
      datasource:
        mysql:
          username: root
          password: 123456
          url: jdbc:mysql://172.16.90.15:3306/commune?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
          driver-class-name: com.mysql.cj.jdbc.Driver
        oracle:
          username: PORTAL
          password: portal
          url: jdbc:oracle:thin:@172.16.90.66:1521/dbtst
          driver-class-name: oracle.jdbc.driver.OracleDriver
  swagger:
    # 扫描的包路径,默认扫描所有
    base-package: com.yuchai.itcommune
    # 如果在生产环境中不想用可以enabled=false，这样一来接口就不存在暴露的风险
    enabled: true

#################### mybatis-plus ###################
mybatis-plus:
  mapper-locations: classpath:/com/yuchai/*/mapper/xml/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

